version: '3.8'

services:
  jenkins-search:
    build: .
    environment:
      - JENKINS_USERNAME
      - JENKINS_API_TOKEN
      - LOG_LEVEL=INFO
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs